### ISSUE TITLE
Improve the findability of file assets via the OAI-PMH record.

### ISSUE THREAD

**Issue by phochste** [ugent-library/oai-service#3] opened 2023-08-09 11:17 UTC
In the dublin core format the `dc:identifier` is used to refer to file assets, but this field is also used for other types of identifiers. Heuristics are currently required to find out what the link to the full text is.

A forward proof solution would accept the fact that oai-pmh dc has this ambiguity and some heuristics should be used to find the landing page of the record. This landing page can then be consulted by agents for SignPosting HTTP headers to find the full text (or via RDFa/Content negotiation find a rdf description which contains more detailed information).

E.g. 

```
curl -I http://hdl.handle.net/1854/LU-01GQ77R3AGST76PDP6FNKTTFGR

HTTP/1.1 200 OK

Link: <http://hdl.handle.net/1854/LU-01GQ77R3AGST76PDP6FNKTTFGR> ; rel="cite-as" , <https://schema.org/ScholarlyArticle> ; rel="type" , 
<https://schema.org/AboutPage> ; rel="type" , <https://orcid.org/0000-0002-1825-0097> ; rel="author" , 
<http://hdl.handle.net/1854/LU-01GQ77R3AGST76PDP6FNKTTFGR/bibtex> ; rel="describedby" ; type="application/x-bibtex" , 
<https://creativecommons.org/licenses/by/4.0/> ; rel="license" ,
<hhttp://hdl.handle.net/1854/LU-01GQ77R3AGST76PDP6FNKTTFGR/file/7507/1> ; rel="item" ; type="application/pdf" , 
<http://hdl.handle.net/1854/LU-01GQ77R3AGST76PDP6FNKTTFGR/file/2> ; rel="item" ; type="text/csv" , 
<http://hdl.handle.net/1854/LU-01GQ77R3AGST76PDP6FNKTTFGR/file/ct.zip> ; rel="item" ; type="application/zip"
```

**Comment by nics** [comment] 2023-08-31 09:42
duplicate of https://github.ugent.be/Universiteitsbibliotheek/biblio/issues/103

**Closed as completed by nics** 2023-08-31 09:42 UTC
